///$tab Main
SET ThousandSep=',';
SET DecimalSep='.';
SET MoneyThousandSep=',';
SET MoneyDecimalSep='.';
SET MoneyFormat='$#,##0.00;-$#,##0.00';
SET TimeFormat='h:mm:ss TT';
SET DateFormat='D/M/YYYY';
SET TimestampFormat='D/M/YYYY h:mm:ss[.fff] TT';
SET FirstWeekDay=6;
SET BrokenWeeks=1;
SET ReferenceDay=0;
SET FirstMonthOfYear=1;
SET CollationLocale='en-AUS';
SET CreateSearchIndexOnReload=0;
SET MonthNames='Jan;Feb;Mar;Apr;May;Jun;Jul;Aug;Sep;Oct;Nov;Dec';
SET LongMonthNames='January;February;March;April;May;June;July;August;September;October;November;December';
SET DayNames='Mon;Tue;Wed;Thu;Fri;Sat;Sun';
SET LongDayNames='Monday;Tuesday;Wednesday;Thursday;Friday;Saturday;Sunday';
SET NumericalAbbreviation='3:k;6:M;9B;12:T;15:P;18:E;21:Z;24:Y;-3:m;-6:μ;-9:n;-12:p;-15:f;-18:a;-21:z;-24:y';

set CurrentFinYear=Yearname(Today(),0,7);


set eFormat= '$' & if(sum($1) >0,
				pick(ceil(log10(sum($1))/3),
                  num(sum($1),'#,##0.0'),
                  num(sum($1)/1E3,'#,##0.0k'),
                  num(sum($1)/1E6,'#,##0.00m'),
                  num(sum($1)/1E9,'#,##0.00b')
                  ),0);

//Todo
//Fix managing region, duplicates in tables
//DESE activities not in fusion causing the manging office to duplicate. Solution ; move managing region calc to load script?
// maybe rationalise offices in description. Talk  to Nicole



///$tab Update Date
[Load Date]:
LOAD
      [Data Source Code] 						AS [Data Source Code]
    , [Siebel Cut Off Date Time] 				AS [Siebel Cut Off Date Time]
    , [Warehouse Load Time] 					AS [Warehouse Load Time]
FROM [lib://Curated Data Store:DataFiles/10 Landing Area/GPS/Data Warehouse Load Time.qvd]
(qvd);



///$tab Acquittal
[Activity Acquittal Amount Temp]:
LOAD
 [Grant Activity Id] 														AS [Grant Activity Id%]
, [Activity Id]  															AS [Temp Activity Id]

FROM [lib://Curated Data Store:DataFiles/10 Landing Area/FUSION/Grant Activity.qvd] (qvd);

LEFT JOIN
LOAD
 [Grant Activity Id] 														AS [Grant Activity Id%]
, [Financial Year Id] 														AS [Financial Year Id%]
, [Funding Amount] 															AS [Total Value (ex GST)]
, [Funds Released] 															AS [Funds Released (ex GST)]

FROM [lib://Curated Data Store:DataFiles/10 Landing Area/FUSION/Grant Activity Funding.qvd] (qvd);

LEFT JOIN
LOAD
  [Financial Year Id] 														AS [Financial Year Id%]
, [Financial Year] 															AS [Activity Financial Year]
FROM [lib://Curated Data Store:DataFiles/10 Landing Area/FUSION/Financial Year.qvd] (qvd);




/*ON PREM Acquittal Days to Completion checks condition on [Acquittal Status] <> 'Complete' (not 'Completed') returning zero matches */ 
[Grant Activity Acquittal Temp]:
LOAD *
	 ,IF( [Temp Acquittal Office] LIKE '*North*', 
     	MID( [Temp Acquittal Office], INDEX(  [Temp Acquittal Office],'North',1)), 
        [Temp Acquittal Office]
        ) 																									AS [Acquittal Office];
LOAD *
	, IF( [Acquittal Due Date] <= TODAY(), 
    	IF( [Acquittal Status] <> 'Completed' , 
        	TODAY(),
            [Acquittal Completion Date] 
          ) - [Acquittal Due Date],
		NULL()
        )		 																							AS [Acquittal Days to Completion] 
    , IF( [Acquittal Due Date] > TODAY() - 30 AND [Acquittal Due Date] < TODAY(), 1, 0) 					AS [Acquittal Due in Last 30 Days]
    , IF( [Acquittal Due Date] < TODAY() + 30 AND [Acquittal Due Date] > TODAY(), 1, 0) 					AS [Acquittal Due in Next 30 Days]
    , IF( [Acquittal Status] LIKE '*Complete*' 
    	AND [Acquittal Completion Date] > TODAY(0) - 8 AND [Acquittal Completion Date] < TODAY(), 1,0) 		AS [Acquittal Completed in Last 7 Days]
    , IF( MATCH( [Review Status] , 'Draft','Scheduled') 
    	AND [Acquittal Status Change Date] > TODAY(0) - 8 , 1, 0)  											AS [Acquittal Created in Last 7 Days]
    , TRIM( LEFT( [Abbrev Milestone Group], INDEX( [Abbrev Milestone Group],'20',1) - 2 )) 					AS [Temp Acquittal Office]
    , YEARNAME( [Acquittal Completion Date], 0, 7)        													AS [Acquittal Completion Financial Year]
;
LOAD
      [Activity Id]  																	AS [Activity Id]
    , [Milestone Id] 																	AS [Milestone Id]
    , [Review Id] 																		AS [Review Id]
    , [Activity Id] &
    	REPLACE([Review Financial Year],'-20','-') 										AS [Activity Acquittal Amount%]
    , [Review Title]																	AS [Grant Activity Acquittal.Review Title]
    , REPLACE([Review Financial Year],'-20','-') 										AS [Acquittal Financial Year]
    , [Review Stage]																	AS [Acquittal Status]
    , [Review Status] 																	AS [Review Status]
    , [Review Due Date]																	AS [Acquittal Due Date]
    , [Review Start Date]																AS [Review Start Date]
    , [Review End Date]																	AS [Review End Date]
    , [Milestone Review Grouping Name]													AS [Milestone Review Grouping Name]
    , [Review Status Change Date]														AS [Acquittal Status Change Date]
    , IF([Review Status] LIKE '*Complete*', 
    	[Review Status Change Date], 
        NULL()) 																		AS [Acquittal Completion Date]
    , NUM([Acquittal Amount]) 															AS [Acquittal Total Value (ex GST)]
    , [Review Item Justification]														AS [Grant Activity Acquittal.Review Item Justification]
    , [Review Result Findings]															AS [Review Result Findings]
    , [Review Result Type]																AS [Review Result Type]
    , [Review Authorised By]															AS [Review Authorised By]
    , [Review Type]																		AS [Grant Activity Acquittal.Review Type]
    , [Review Subtype]																	AS [Review Subtype]
    , REPLACE(
    	MID( [Milestone Review Grouping Name], 
    		INDEX( [Milestone Review Grouping Name], 'Acquittal', 1) +10 ),
		'&' ,
        'and') 																			AS [Abbrev Milestone Group]

FROM [lib://Curated Data Store:DataFiles/10 Landing Area/GPS/Grant Activity Acquittal.qvd] (qvd)
WHERE NOT MATCH([Review Status], 'Cancelled');

LEFT JOIN
LOAD
	  [Temp Activity Id]&[Activity Financial Year] 										AS [Activity Acquittal Amount%]
	, NUM([Total Value (ex GST)]) 														AS [Activity Acquittal Total Value (ex GST)]
RESIDENT [Activity Acquittal Amount Temp];






[Grant Activity Acquittal]:
LOAD DISTINCT *, 
	IF(ISNULL([Acquittal Total Value (ex GST)]), 
    	[Activity Acquittal Total Value (ex GST)],
        [Acquittal Total Value (ex GST)]
        ) 														AS [Acquittal Forecast Value (ex GST)]
RESIDENT [Grant Activity Acquittal Temp];

DROP TABLE [Activity Acquittal Amount Temp];

[Grant Activity Acquittal-3]:
LOAD
      [Review Id] 												AS [Review Id]
    , [Review Title] 											AS [Review Title]
    , [Review Item Number] 										AS [Review Item Number]
    , [Review Item Question] 									AS [Review Item Question]
    , [Review Item Answer] 										AS [Review Item Answer]
    , [Review Item Justification] 								AS [Review Item Justification]
    
FROM [lib://Curated Data Store:DataFiles/10 Landing Area/GPS/Grant Activity Acquittal Item.qvd] (qvd);





//Create Master calendar based on reviews/Acquittals
[OverdueRevAcquittalDates]:
//create a date for each day the review is not complete
LOAD *
    , [Rev End Date] - [Rev Due Date] 												AS [No of Days Open]
    , DATE([Rev Due Date] + IterNo() - 1) 											AS [RevOverdueDate]
           	WHILE [Rev Due Date] + IterNo() - 1 <= [Rev End Date];
LOAD
      [Review Id]
    , [Acquittal Due Date] 															AS [Rev Due Date]
    , IF([Acquittal Due Date] < TODAY() AND NOT [Review Status] LIKE 'Complete*', 
    	TODAY(), 
     	IF([Review Status] LIKE 'Complete*',  
        	[Acquittal Status Change Date],
            NULL())
         ) 																			AS [Rev End Date] 
RESIDENT [Grant Activity Acquittal Temp];





[MinMax]:
LOAD 
	  MIN([RevOverdueDate]) 													AS [MinDate]
	, MAX([Rev End Date]) 														AS [MaxDate]
RESIDENT [OverdueRevAcquittalDates];

LET vMinDate = PEEK('MinDate',0,'Min_Max');
LET vMaxDate = PEEK('MaxDate',0, 'Min_Max');

DROP TABLE [MinMax];



[Temp1]:
LOAD 
	DATE($(vMinDate) + RowNo() - 1) 											AS [RDay]
	AutoGenerate (1)
		WHILE $(vMinDate) + IterNo() -1 <= $(vMaxDate);



[RevFortnightEnding]:
LOAD 
	[RDay] 																		AS [RevOverdueDate]
	,'Q' & CEIL(NUM(MONTH([RDay]))/3) 											AS [RevOverdueQuarter]
 	, DUAL('Q'&	NUM(CEIL(NUM(MONTH(AddMonths([RDay],1-7)))/3)),
    			NUM(CEIL(NUM(MONTH(AddMonths([RDay],1-7)))/3),00)) 				AS [Fiscal_Quarter]
	, YEAR(DATE([RDay])) 														AS [RevOverdueYear]
	, MONTHNAME([RDay]) 														AS [RevOverdueMonthYear]
	, WEEK([RDay]) 																AS [RevOverdueWeek]
	, WEEKEND([RDay], 0, 4) 													AS [RevOverdueWeekEnd]
	, WEEKYEAR([RDay]) 															AS [RevOverdueWeekYear]
	, YEARNAME([RDay], 0, 7) 													AS [FinancialYear]
	, IF(MOD(WEEK([RDay], 0, 7), 2) = 0, 
    	DATE(WEEKEND(RDay, 1, 7)), 
        DATE(WEEKEND(RDay, 0, 7))) 												AS [RevFortnightEnding]
RESIDENT [Temp1];

DROP TABLE [Temp1];
DROP TABLE [Grant Activity Acquittal Temp];




///$tab Activity
[Grant Activity Temp]:
LOAD
      [Grant Activity Id] 																		AS [Grant Activity Id%]
    , [Source Organisation Id] 																	AS [Activity Source Organisation Id%]
    , IF( [Activity Id] = '4-ENJBSQ2', 'a6c824bf-afc1-e611-80f1-c4346bc5977c',[PMC Region Id]) 	AS [PMC Region Id%] /*Is this still necessary?*/
	, [Programme Component Id] 																	AS [Programme Component Id%]
	, IF( LEN( [Programme Id]) = 0, 'ae0b9448-9f69-e611-80e6-c4346bc43f98',[Programme Id])  	AS [Programme Id%]
	, [Sub Programme] 																			AS [Sub Program]
	, [Grant Activity] 																			AS [Activity Title]
    , [Activity Id] 																			AS [Activity Id]
    , [Activity Description] 																	AS [Long Description]
    , DATE( [Activity Start Date], 'DD/MM/YYYY') 												AS [Activity Start Date]
    , DATE( [Activity End Date], 'DD/MM/YYYY') 													AS [Activity End Date]
    , YEARNAME([Activity End Date], 0,7) 														AS [Activity End Date Fin Year]
    , IF( 	[Activity Start Date]  > TODAY() - 30 												
    	AND [Activity Start Date]  < TODAY(), 1,0) 												AS [Activity started in last 30 days]
    , IF(	[Activity End Date]  > TODAY() - 30 												
    	AND [Activity End Date]  < TODAY(), 1,0) 												AS [Activity ended in last 30 days]
    , [Source System Id]																		//AS
    , [Activity Manager] 																		AS [Activity Manager]
    , lower( Trim( [Activity Manager])) 														AS [Activity Manager Key] 
    , [Approved On Date]																		//AS
	, [Source Status Group] 																	AS [Activity Status]
    , [Current Ceasing Activity Assessment Id]													//AS
    , [Current Ceasing Activity Assessment]														//AS
FROM [lib://Curated Data Store:DataFiles/10 Landing Area/FUSION/Grant Activity.qvd] (qvd);

Left Join
LOAD
      [Source Organisation Id]  											AS [Activity Source Organisation Id%]
    , [Organisation Id]  													AS [Activity Organisation Id%]
    
FROM [lib://Curated Data Store:DataFiles/10 Landing Area/FUSION/Source Organisation.qvd] (qvd);

Left Join
LOAD
      [Organisation Id]  										AS [Activity Organisation Id%]
    , [Organisation]  											AS [Activity Organisation]
    , [ABN]  													AS [Activity ABN]
    , [ORP Expiry Date]  										AS [Activity ORP Expiry Date]
    , IF(ISNULL([ORP Risk Rating]), 'Not Rated', IF([ORP Expiry Date]<TODAY(), 'Expired', [ORP Risk Rating]))  AS [Activity Organisation Risk Profile]  
    , [Risk Exemption Reason]  									AS [Actitivy Risk Exemption Reason]
    , IF(IsNull([Indigeneity]) or [Indigeneity] = 'Unknown' , 'No', [Indigeneity])  AS [Organisation Indigeneity]
    
FROM [lib://Curated Data Store:DataFiles/10 Landing Area/FUSION/Organisation.qvd] (qvd);

Left Join
LOAD
	  [Programme Id]  											AS [Programme Id%]
	, REPLACE([Programme],'2.','1.')  							AS [Program]

FROM [lib://Curated Data Store:DataFiles/10 Landing Area/FUSION/Programme.qvd] (qvd);

Left Join
LOAD
	  [Programme Component Id]  								AS [Programme Component Id%]
	, [Programme Id]  											AS [Programme Id%]
	, [Programme Component]										//AS
 	, [Outcome Element] 			 							AS [Outcome Element]
    
FROM [lib://Curated Data Store:DataFiles/10 Landing Area/FUSION/Programme Component.qvd] (qvd);



[Grant Activity Funding]:
LOAD
	  [Grant Activity Id]  						AS [Grant Activity Id%]
 	, [Financial Year Id]  						AS [Financial Year Id%]
	, [Funding Amount]  						AS [Total Value (ex GST)]
    , [Funds Released]  						AS [Funds Released (ex GST)]
FROM [lib://Curated Data Store:DataFiles/10 Landing Area/FUSION/Grant Activity Funding.qvd] (qvd);

Left Join
LOAD
      [Financial Year Id]  						AS [Financial Year Id%]
    , [Financial Year]  						AS [Activity Funding Financial Year]
FROM [lib://Curated Data Store:DataFiles/10 Landing Area/FUSION/Financial Year.qvd] (qvd);




[Grant Activity]:
LOAD
      [Grant Activity Id%]
    , [Activity Id]
    , [Activity Organisation Id%]
    , [Activity Organisation]
    , [Activity ABN]
    , [Organisation Indigeneity]
    , [Activity Organisation Risk Profile]
    , [Activity ORP Expiry Date]
    , [Activity Title]
    , [Activity Status]
    , IF([Outcome Element] = 'ABA', 'Aboriginals Benefit Account', [Program])  			AS [Program]
    , [Sub Program]
    , [Activity Start Date]
    , [Activity End Date]
    , [Activity End Date] - [Activity Start Date]  										AS [Activity Duration]
    , [Activity Manager]
    , [Activity started in last 30 days]
    , [Activity ended in last 30 days]
    , [Activity End Date Fin Year]

RESIDENT [Grant Activity Temp];

DROP TABLE [Grant Activity Temp];



LatestFinYear:
LOAD *,
	'20' & [LatestFinYear] - 1 & '-'& [LatestFinYear]  		AS 	[Latest Funding Financial Year];
LOAD 
	  [Grant Activity Id%]
	, MAX(RIGHT([Activity Funding Financial Year], 2))  	AS [LatestFinYear]
RESIDENT [Grant Activity Funding]
GROUP BY [Grant Activity Id%];



///$tab Region
RegionMap:
MAPPING LOAD  *
INLINE [Region, Group
	Adelaide - GMU, Central
	Alice Springs - GMU,Central
    Arnhem Land & Groote Eylandt, Central
    Darwin - GMU,	Central
    Central Australia,	Central
    Top End & Tiwi Islands,	Central
    Brisbane - GMU,	Eastern
    Cairns - GMU,	Eastern
    Dubbo - GMU,	Eastern
    Mount Isa - GMU,	Eastern
    Orange - GMU,	Eastern
    Parramatta - GMU,	Eastern
    Tamworth - GMU,	Eastern
    Townsville - GMU,	Eastern
    Eastern NSW,	Eastern
    Eastern New South Wales, Eastern
    Western New South Wales, Eastern
    North Queensland,	Eastern
    South Queensland,	Eastern
    Eastern New South Wales,  Eastern
    Western NSW,	Eastern
    Broome - GMU,	National Office
    Canberra - GMU,	National Office
    Coffs Harbour - GMU,	National Office
    National Office,	National Office
    Adelaide - GMU,	West and South
    Melbourne - GMU,	West and South
    Perth - GMU,	West and South
    Greater Western Australia,	West and South
    Kimberley, West and South
    South Australia,	West and South
    Victoria & Tasmania,	West and South
    GMU Central Support - GMU, National Office
];


[Grant Managing Region_temp]:
LOAD
      [Grant Activity Id]					AS [Grant Activity Id%]
    , [Activity Id]							AS [Activity Id]    
	, [Engagement Office Id] 				AS [NIAA Region Id%]    
    , [PMC Region Id] 						AS [GMU Region Id%]
    , [Engagement Officer]					AS [Engagement Officer]
    , [Source System Id]					AS [Source System Id%]		  
FROM [lib://Curated Data Store:DataFiles/10 Landing Area/FUSION/Grant Activity.qvd] (qvd);
LEFT JOIN 
LOAD
    [Source System Id]        	AS [Source System Id%],
    [Source System]				AS [Source System]
FROM [lib://Curated Data Store:DataFiles/10 Landing Area/FUSION/Source System.qvd] (qvd);

[Grant Managing Region]:
LOAD
      [Grant Activity Id%]
    , [NIAA Region Id%] 					AS [PMC Region Id%]
    , [GMU Region Id%]
    , [Engagement Officer]
    , [Source System]
RESIDENT [Grant Managing Region_temp];

DROP TABLE [Grant Managing Region_temp];




[NIAA Region]:
LOAD *,
	applymap('RegionMap',[NIAA Region]) 																	AS [Group];
LOAD
      [PMC Region Id] 																						AS [PMC Region Id%]
    , IF(MATCH([PMC Region Abbr], 'FNQLD', 'GNQLD'), [PMC Region]) 											AS [NIAA Sub Region]
    , IF(MATCH([PMC Region Abbr], 'FNQLD', 'GNQLD'), [PMC Region Abbr]) 									AS [NIAA Sub Region Abbr]
    , IF(MATCH([PMC Region Abbr], 'FNQLD', 'GNQLD'), 'North Queensland', [PMC Region]) 						AS [NIAA Region]
    , IF(MATCH([PMC Region Abbr], 'FNQLD', 'GNQLD'), 'NQ', [PMC Region Abbr]) 								AS [PMC Region.PMC Region Abbr]
    , [State]
	, IF(	[PMC Region Abbr] = 'GWA' 	
    	OR 	[PMC Region Abbr] = 'KIM' 	
        OR 	[PMC Region Abbr] = 'SA' 
        OR 	[PMC Region Abbr] = 'VIC/TAS', 
        'West & South Group',
	  IF(	[PMC Region Abbr] = 'CA' 	
      	OR 	[PMC Region Abbr] = 'TETI' 	
        OR 	[PMC Region Abbr] = 'ALGE', 
        'Central Group',
	 IF(	[PMC Region Abbr] = 'ENSW' 	
     	OR 	[PMC Region Abbr] = 'WNSW' 	
        OR 	[PMC Region Abbr] = 'SQLD' 
		OR 	[PMC Region Abbr] = 'FNQLD' 	
        OR 	[PMC Region Abbr] = 'GNQLD', 
        'Eastern Group','National'))) 																		AS [NIAA Region Group]

FROM [lib://Curated Data Store:DataFiles/10 Landing Area/FUSION/PMC Region.qvd] (qvd);



[GMU Region]:

LOAD
      [PMC Region Id] 								AS [GMU Region Id%]
    , [State] 										AS [GMU State]
	, IF(	[PMC Region Abbr] = 'GWA' 
    	OR 	[PMC Region Abbr] = 'KIM' 
        OR	[PMC Region Abbr] = 'SA' 
        OR 	[PMC Region Abbr] = 'VIC/TAS', 
        'West & South Group'
	, IF(	[PMC Region Abbr] = 'CA' 
    	OR 	[PMC Region Abbr] = 'TETI' 
        OR 	[PMC Region Abbr] = 'ALGE', 
        'Central Group'
	, IF(	[PMC Region Abbr] = 'ENSW' 
    	OR 	[PMC Region Abbr] = 'WNSW' 
        OR 	[PMC Region Abbr] = 'SQLD' 
        OR 	[PMC Region Abbr] = 'FNQLD' 
		OR 	[PMC Region Abbr] = 'GNQLD', 
        'Eastern Group','National'))) 				AS [GMU Region Group]

FROM [lib://Curated Data Store:DataFiles/10 Landing Area/FUSION/PMC Region.qvd] (qvd);




///$tab Milestone
[Grant Activity Milestone]:

LET vDaysoverdue = 'IF([Milestone Expected Due Date] <= TODAY(), TODAY() - [Milestone Expected Due Date])' ;
LET vEndDate = text('2014-06-30');
LET vLastYear = NUM(YEAR(TODAY()) - 1);

LOAD 
	  $(vDaysoverdue) 																	AS [Number of Days Milestone Overdue]		
	, [Activity Id] 																	AS [Grant Activity Milestone.Activity Id]
    , REPLACE(YEARNAME([Milestone Expected Due Date],0,7), '-20','-') 					AS [Milestone Financial Year]
    , [Activity PBS Program] 															AS [Activity PBS Outcome]
    , [Managing Office - Activity] 														AS [Milestone Managing Office%]
    , [Milestone Id] 																	AS [Milestone Id]
    , [Milestone Status] 																AS [Milestone Status]
    , IF( [Milestone Expected Due Date] > TODAY(), 'Overdue',  [Milestone Stage]) 		AS [Milestone Stage]
    , [Milestone Completed Indicator] 													AS [Milestone Completed Indicator]
    , [Milestone Payment Mode] 															AS [Milestone Payment Mode]
    , [Milestone Received] 																AS [Milestone Received]
    , [Milestone Short Description] 													AS [Milestone Short Description]
    , [Milestone Long Description] 														AS [Milestone Long Description]
    , [Milestone Completion Description] 												AS [Milestone Completion Description] 
    , [Milestone Type] 																	AS [Milestone Type]
    , (Floor(([Milestone Completion Date] - [Milestone Expected Due Date])/30) * 30)+30 AS [Days to Complete]
    , [Milestone Expected Due Date] 													AS [Milestones Expected Due Date]
    , [Financial Year Name] 															AS [Financial Year Name]
    , [Milestone Action Required] 														AS [Milestone Action Required]
    , [Milestone Completion Date] 														AS [Milestone Completion Date]
    , [Activity IMPACT PO Id] 															AS [Activity IMPACT PO Id]
    , [Milestone Auto Release Indicator] 												AS [Milestone Auto Release Indicator]
    , [Milestone Date Driven Indicator] 												AS [Milestone Date Driven Indicator]
    , [Milestone Actual Amount Ex GST] 													AS [Milestone Actual Amount Ex GST]
	, IF( [Milestone Expected Due Date] > TODAY(), 0, 1) 								AS [Overdue by Date]
	, IF( [Milestone Expected Due Date] <= TODAY(), 
        IF( [Milestone Stage] = 'Future',
        	'Overdue - Not received',
          	IF( [Milestone Stage] = 'Overdue', 
				'Overdue - Not received',
              	IF( [Milestone Stage] = 'Received', 
          	    	'Overdue - Received'))),
    	IF( [Milestone Expected Due Date] > TODAY(),
        	IF( [Milestone Stage] = 'Future', 
            	'Future - Not received',
            	IF( [Milestone Stage] = 'Overdue', 
            		'Future - Not received',
            		IF( [Milestone Stage] = 'Received',  
            			'Future - Received'))))) 										AS [Stage]
    , IF(	[Milestone Expected Due Date] < TODAY() + 30 
    	AND [Milestone Expected Due Date] > TODAY(), 1, 0) 								AS [Due in next 30 Days]
    , IF(	[Milestone Expected Due Date] < TODAY() + 180 
    	AND [Milestone Expected Due Date] > TODAY(), 1, 0) 								AS [Due in next 6 Months]
    , IF(	[Milestone Expected Due Date] < TODAY() + 60 
    	AND [Milestone Expected Due Date] > TODAY() + 30, 1, 0) 						AS [Due in next 60 Days]
    , IF(	[Milestone Completion Date]   > TODAY() - 30 
    	AND [Milestone Expected Due Date] < TODAY(), 1, 0) 								AS [Completed in last 30 Days]
    , IF($(vDaysoverdue) <= 30, 1, 0) 													AS [Due in last 30 Days]

FROM [lib://Curated Data Store:DataFiles/10 Landing Area/GPS/Grant Activity Milestone - Old.qvd] (qvd)

WHERE [Activity Execution State] = 'Executed' 
	AND [Milestone Status] = 'Current' 
	AND Match([Activity Status], 'Approved' , 'Varied' , 'Ready for Approval')
	AND ([Activity PBS Program] <>  'DPMC SOETM Services for Other Entities and Trust Monies')
	AND (	[Milestone Type] 			 LIKE '*Acquittal*' 
    	OR 	[Milestone Long Description] LIKE '*Acquittal*');


[Milestone Count]:
NoConcatenate LOAD 
	  COUNT([Milestone Id]) 											AS [Milestone Count]
	, [Grant Activity Milestone.Activity Id] 							AS [Activity Id]
RESIDENT [Grant Activity Milestone]
GROUP BY [Grant Activity Milestone.Activity Id]; 
 


[Milestone Overdue Month]:
LOAD
	  [Milestone Id]
	, [Milestone Payment Mode] 											AS [Overdue Payment Mode]
	, DATE(Outstanding, 'dd/MM/yyyy') 									AS [Milestone Outstanding]
	, REPLACE(YEARNAME(Outstanding,0,7), '-20','-') 					AS [Overdue Milestone Financial Year]
FROM [lib://Curated Data Store:DataFiles/10 Landing Area/GPS/Milestone Overdue Month.qvd] (qvd);




///$tab Quality
[Grant Activity Acquittal Error]:
LOAD
      [Review Id] 											AS [Review Id]
    , [Error] 												AS [Review Error]
    , [Error Number] 										AS [Error Number]

FROM [lib://Curated Data Store:DataFiles/10 Landing Area/GPS/Grant Activity Acquittal Error.qvd] (qvd);


//Check for missing acquittals by comparing the number of financial years with the number of reviews 
[FinYearCount]:
LOAD 
	  [Grant Activity Id%]
	, COUNT([Activity Funding Financial Year]) 				AS [FundingYrCount]
RESIDENT [Grant Activity Funding]
	WHERE NUM(LEFT([Activity Funding Financial Year], 4)) > 2016
	AND   NUM(LEFT([Activity Funding Financial Year], 4)) <= NUM(LEFT(YEARNAME(NOW(2), 0, 7), 4)) //Exclude next financial year
	GROUP BY [Grant Activity Id%];

LEFT JOIN
LOAD 
	  [Grant Activity Id%]
	, [Activity Id]
RESIDENT [Grant Activity];



[Acquittal Count]:
LOAD 
	  [Activity Id]							AS [Activity Id]
	, COUNT([Review Id]) 					AS [ReviewCount]
RESIDENT [Grant Activity Acquittal]
GROUP BY [Activity Id];


[Stg_MissingAcquittals]:
LOAD 
	  [Activity Id]
	, [FundingYrCount]
RESIDENT [FinYearCount];

left Join 
LOAD 
	  [Activity Id]
	, [ReviewCount]
RESIDENT [Acquittal Count];

[MissingAcquittals]:
LOAD 
	  [Activity Id]
	, [FundingYrCount]
    , [ReviewCount]
    , IF([FundingYrCount] > alt([ReviewCount], 0), 'Check', 'Ok') 	AS [Potential Missing Acquittal]
RESIDENT [Stg_MissingAcquittals];
	

DROP TABLES [Acquittal Count], [FinYearCount], [Stg_MissingAcquittals];



///$tab Exit
exit script;