///$tab Main
SET ThousandSep = ',';
SET DecimalSep = '.';
SET MoneyThousandSep = ',';
SET MoneyDecimalSep = '.';
SET MoneyFormat = '$#,##0.00;-$#,##0.00';
SET TimeFormat = 'h:mm:ss TT';
SET DateFormat = 'D/M/YYYY';
SET TimestampFormat = 'D/M/YYYY h:mm:ss[.fff] TT';
SET FirstWeekDay = 6;
SET BrokenWeeks = 1;
SET ReferenceDay = 0;
SET FirstMonthOfYear = 1;
SET CollationLocale = 'en-AUS';
SET CreateSearchIndexOnReload = 0;
SET MonthNames = 'Jan;Feb;Mar;Apr;May;Jun;Jul;Aug;Sep;Oct;Nov;Dec';
SET LongMonthNames = 'January;February;March;April;May;June;July;August;September;October;November;December';
SET DayNames = 'Mon;Tue;Wed;Thu;Fri;Sat;Sun';
SET LongDayNames = 'Monday;Tuesday;Wednesday;Thursday;Friday;Saturday;Sunday';
SET NumericalAbbreviation = '3:k;6:M;9B;12:T;15:P;18:E;21:Z;24:Y;-3:m;-6:μ;-9:n;-12:p;-15:f;-18:a;-21:z;-24:y';
// directory lib://AppData/DEV/AzureDataLake/GPS/; 
	DIRECTORY LIB://AppDataProd/AzureDataLake/GPS/; 
	SET CurrentFinYear = YEARNAME(TODAY(), 0, 7);


SET eFormat = '$' & IF(SUM($1) > 0,
PICK(CEIL(LOG10(SUM($1)) / 3),
                  NUM(SUM($1), '#,##0.0'),
                  NUM(SUM($1) / 1E3, '#,##0.0k'),
                  NUM(SUM($1) / 1E6, '#,##0.00m'),
                  NUM(SUM($1) / 1E9, '#,##0.00b')
), 0);

//Todo
//Fix managing region, duplicates in tables
//DESE activities not in fusion causing the manging office to duplicate. Solution ; move managing region calc to load script?
// maybe rationalise offices in description. Talk  to Nicole
//Changes
//Fixed acquittal amounts and counts on summary sheet
//fixed amounts and colours on open acquittals by groups sheet.
//restricted  milestones on the details sheet to milestones linked to an acquittal
//removed milestone processing not used in the table. the code is commented out and should be deleted if not required.
//added tool tip to data quality bar chart showing error.



///$tab Update Date
	[Load Date]:
	LOAD
		  [Data Source Code]			 AS [Data Source Code]
		, [Siebel Cut Off Date Time]	 AS [Siebel Cut Off Date Time]
		, [Warehouse Load Time]			 AS [Warehouse Load Time]
	FROM [lib://Curated Data Store:DataFiles/10 Landing Area/GPS/Data Warehouse Load Time.qvd] (qvd);
///$tab Acquittal
	[Activity Acquittal Amount Temp]:
	LOAD
		  [Grant Activity Id]	 AS [Grant Activity Id%]
		, [Activity Id]			 AS [Temp Activity Id]
	FROM [lib://Curated Data Store:DataFiles/10 Landing Area/FUSION/Grant Activity.qvd] (qvd);


	LEFT JOIN
	LOAD
		  [Grant Activity Id]	 AS [Grant Activity Id%]
		, [Financial Year Id]	 AS [Financial Year Id%]
		, [Funding Amount]		 AS [Total Value (ex GST)]
		, [Funds Released]		 AS [Funds Released (ex GST)]
	FROM [lib://Curated Data Store:DataFiles/10 Landing Area/FUSION/Grant Activity Funding.qvd] (qvd);


	LEFT JOIN
	LOAD
		  [Financial Year Id]	 AS [Financial Year Id%]
		, [Financial Year]		 AS [Activity Financial Year]
	FROM [lib://Curated Data Store:DataFiles/10 Landing Area/FUSION/Financial Year.qvd] (qvd);


	[Grant Activity Acquittal Temp]:
	LOAD *
		, IF([Temp Acquittal Office] LIKE '*North*', MID([Temp Acquittal Office], INDEX([Temp Acquittal Office], 'North', 1)), [Temp Acquittal Office]) AS [Acquittal Office];


	LOAD *
		, IF([Acquittal Due Date] <= TODAY(),
			IF([Acquittal Status] <> 'Complete', TODAY(), [Acquittal Completion Date]) - [Acquittal Due Date])	 AS [Acquittal Days to Completion]
		, IF([Acquittal Due Date] > TODAY() - 30 AND [Acquittal Due Date] < TODAY(), 1, 0)						 AS [Acquittal Due in Last 30 Days]
		, IF([Acquittal Due Date] < TODAY() + 30 AND [Acquittal Due Date] > TODAY(), 1, 0)						 AS [Acquittal Due in Next 30 Days]
		, IF([Acquittal Status] LIKE '*Complete*' AND [Acquittal Completion Date] > TODAY(0) - 8 AND [Acquittal Completion Date] < TODAY(), 1, 0) AS [Acquittal Completed in Last 7 Days]
		, IF(MATCH([Review Status], 'Draft', 'Scheduled'/*'In Progress', */) AND [Acquittal Status Change Date] > TODAY(0) - 8, 1, 0) AS [Acquittal Created in Last 7 Days]
		, TRIM(LEFT([Abbrev Milestone Group], INDEX([Abbrev Milestone Group], '20', 1) - 2))					 AS [Temp Acquittal Office];


	LOAD [Activity Id] AS [Activity Id]
		, [Milestone Id]																			 AS [Milestone Id]
		, [Review Id]																				 AS [Review Id]
		, [Activity Id] & REPLACE([Review Financial Year], '-20', '-')	 AS [Activity Acquittal Amount%]
		, [Review Title]																			 AS [Grant Activity Acquittal.Review Title]
		, REPLACE([Review Financial Year], '-20', '-')												 AS [Acquittal Financial Year]
//		, [Grant Activity Acquittal.Acquittal Status]																		 AS [Acquittal Status]
//		, IF([Grant Activity Acquittal.Review Status] = 'Complete Pending Activities', 'Complete',
//			IF([Grant Activity Acquittal.Review Status] = 'In Progress' OR [Grant Activity Acquittal.Review Status] = 'Planned'
//			OR [Grant Activity Acquittal.Review Status] = 'Received - In Progress' OR [Grant Activity Acquittal.Review Status] = 'Scheduled'
//			OR [Grant Activity Acquittal.Review Status] = 'Submitted', 'Due',
//			[Grant Activity Acquittal.Review Status]))																		 AS [Acquittal Status]
//		, IF([Grant Activity Acquittal.Review Status] LIKE 'Complete*', 'Complete',
//			IF([Grant Activity Acquittal.Review Due Date] > TODAY(), 'Future', 'Due'))										 AS [Acquittal Status]
		, [Review Stage]																			 AS [Acquittal Status]
		, [Review Status]																			 AS [Review Status]
		, [Review Due Date]																		 AS [Acquittal Due Date]
//		, IF([Grant Activity Acquittal.Review Due Date] > TODAY(), NULL(), IF([Grant Activity Acquittal.Review Status] = 'Complete'
//			OR [Grant Activity Acquittal.Review Status] = 'Complete Pending Activities', [Grant Activity Acquittal.Review Status Change Date], TODAY()) - [Grant Activity Acquittal.Review Due Date])																												 AS [Acquittal Days to Completion]
//		, IF([Grant Activity Acquittal.Review Due Date] > TODAY() - 30 AND [Grant Activity Acquittal.Review Due Date] < TODAY(), 1, 0) AS [Acquittal Due in Last 30 Days]
//		, IF([Grant Activity Acquittal.Review Due Date] < TODAY() + 30 AND [Grant Activity Acquittal.Review Due Date] > TODAY(), 1, 0) AS [Acquittal Due in Next 30 Days]
		, [Review Start Date]																		 AS [Grant Activity Acquittal.Review Start Date]
		, [Review End Date]																		 AS [Grant Activity Acquittal.Review End Date]
		, [Milestone Review Grouping Name]															 AS [Milestone Review Grouping Name]
		, [Review Status Change Date]																 AS [Acquittal Status Change Date]
		, IF([Review Status] LIKE '*Complete*', [Review Status Change Date]) AS [Acquittal Completion Date]
		, YEARNAME(IF([Review Status] LIKE '*Complete*', [Review Status Change Date]), 0, 7) AS [Acquittal Completion Financial Year]
		, NUM([Acquittal Amount])																	 AS [Acquittal Total Value (ex GST)]
//		, IF(NUM([Grant Activity Acquittal.Acquittal Amount]) <= 0, 1, 0)													 AS [Acquittal Amount Not Entered]
		, [Review Item Justification]																 AS [Grant Activity Acquittal.Review Item Justification]
		, [Review Result Findings]																	 AS [Review Result Findings]
		, [Review Result Type]																		 AS [Review Result Type]
		, [Review Authorised By]																	 AS [Grant Activity Acquittal.Review Authorised By]
		, [Review Type]																			 AS [Grant Activity Acquittal.Review Type]
		, [Review Subtype]																			 AS [Grant Activity Acquittal.Review Subtype]
		, REPLACE(MID([Milestone Review Grouping Name], INDEX([Milestone Review Grouping Name], 'Acquittal', 1) + 10), '&', 'and') AS [Abbrev Milestone Group]
//		, [Grant Activity Acquittal.Activity End Date]																		 AS [Grant Activity Acquittal.Activity End Date]
	FROM [lib://Curated Data Store:DataFiles/10 Landing Area/GPS/Grant Activity Acquittal.qvd] (qvd)
	WHERE NOT MATCH([Review Status], 'Cancelled') ;


	LEFT JOIN
	LOAD
		  [Temp Activity Id] & [Activity Financial Year]	 AS [Activity Acquittal Amount%]
		, NUM([Total Value (ex GST)])						 AS [Activity Acquittal Total Value (ex GST)]
	RESIDENT [Activity Acquittal Amount Temp];


// [Grant Acquittal Trend]:
// Load distinct [Review Id], 
// 	date(MonthEnd(ActiveDateAcq), 'MMM-YY') as RevOverdueMonthYear
//     where ActiveDateAcq > today(2) - 730
// //     and [Acquittal Status] = 'Due'
// //     and [Trend Acquittal Due Date] < ActiveDateAcq
//     ;
// LOAD [Review Id],
// 		[Acquittal Due Date] as [Trend Acquittal Due Date],
//         if(isnull([Acquittal Completion Date]), today(2), [Acquittal Completion Date]) as [Trend Acquittal Status Change Date],
//         //[Acquittal Status Change Date] as [Trend Acquittal Status Change Date],
//         [Acquittal Status] as [Trend Acquittal Status],
// 		[Acquittal Due Date] + IterNo()-1  as ActiveDateAcq,
//         IterNo()-1 as [Acquittal Days],
//         [Acquittal Status]
//     //    (Floor((IterNo()-1)/30) * 30)+30 as [AquittalBins]
//             While [Acquittal Due Date] + IterNo()-1 <= IF([Acquittal Status] = 'Complete', [Acquittal Status Change Date], TODAY(2))
//             ;
// LOAD *
// Resident [Grant Activity Acquittal Temp];
	[Grant Activity Acquittal]:
	LOAD DISTINCT *
		, IF(ISNULL([Acquittal Total Value (ex GST)]), [Activity Acquittal Total Value (ex GST)], [Acquittal Total Value (ex GST)]) AS [Acquittal Forecast Value (ex GST)]
	RESIDENT [Grant Activity Acquittal Temp];


	DROP TABLE [Activity Acquittal Amount Temp];


	LOAD
		  [Review Id]					 AS [Review Id]
		, [Review Title]				 AS [Grant Activity Acquittal Item.Review Title]
		, [Review Item Number]		 AS [Review Item Number]
		, [Review Item Question]		 AS [Review Item Question]
		, [Review Item Answer]		 AS [Review Item Answer]
		, [Review Item Justification]	 AS [Review Item Justification]
	FROM [lib://Curated Data Store:DataFiles/10 Landing Area/GPS/Grant Activity Acquittal Item.qvd] (qvd);


//Create Master calendar based on reviews/Acquittals
	OverdueRevAcquittalDates:
//create a date for each day the review is not complete
	LOAD *
		, [Rev End Date] - [Rev Due Date]		 AS [No of Days Open]
		, DATE([Rev Due Date] + ITERNO() - 1)	 AS [RevOverdueDate]
			WHILE [Rev Due Date] + ITERNO() - 1 <= [Rev End Date];


//Today();
	LOAD
		  [Review Id]																 AS [Review Id]
		, [Acquittal Due Date]														 AS [Rev Due Date]
//set overdue flag
//If("Review Due Date"< today()  and  not "Review Status" like 'Complete*', 'Y', 'N') as "Overdue Acquittal",
// check if review is completed
		, IF([Acquittal Due Date] < TODAY() AND NOT [Review Status] LIKE 'Complete*', TODAY(),
			IF([Review Status] LIKE 'Complete*', [Acquittal Status Change Date]))	 AS [Rev End Date]
	RESIDENT [Grant Activity Acquittal Temp]; //[Dim Review]
//where "Review Status" <> 'Complete' Or  if("Review Status" = 'Complete', "Review Status Change Date") -  "Review Due Date" > 0;


	MinMax:
	LOAD MIN([RevOverdueDate]) AS [MinDate]
		, MAX([Rev End Date])	 AS [MaxDate]
	RESIDENT OverdueRevAcquittalDates;

LET vMinDate = PEEK('MinDate', 0, 'Min_Max');
LET vMaxDate = PEEK('MaxDate', 0, 'Min_Max');
	DROP TABLE MinMax;


	Temp1:
	LOAD
		  DATE($([vMinDate]) + ROWNO() - 1)	 AS [RDay]
	AUTOGENERATE (1)
	WHILE $(vMinDate) + ITERNO() - 1 <= $(vMaxDate);


	RevFortnightEnding:
	LOAD
		  [RDay]																						 AS [RevOverdueDate]
		, 'Q' & CEIL(NUM(MONTH([RDay])) / 3)															 AS [RevOverdueQuarter]
		, DUAL('Q' & NUM(CEIL(NUM(MONTH(ADDMONTHS([RDay], 1 - 7))) / 3)), NUM(CEIL(NUM(MONTH(ADDMONTHS([RDay], 1 - 7))) / 3), 00)) AS [Fiscal_Quarter]
		, YEAR(DATE([RDay]))																			 AS [RevOverdueYear]
		, MONTHNAME([RDay])																				 AS [RevOverdueMonthYear]
		, WEEK([RDay])																					 AS [RevOverdueWeek]
		, WEEKEND([RDay], 0, 4)																			 AS [RevOverdueWeekEnd]
		, WEEKYEAR([RDay])																				 AS [RevOverdueWeekYear]
		, YEARNAME([RDay], 0, 7)																		 AS [FinancialYear]
		, IF(MOD(WEEK([RDay], 0, 7), 2) = 0, DATE(WEEKEND([RDay], 1, 7)), DATE(WEEKEND([RDay], 0, 7)))	 AS [RevFortnightEnding]
	RESIDENT Temp1;


	DROP TABLE Temp1;


	DROP TABLE [Grant Activity Acquittal Temp];

///$tab Activity
	[Grant Activity Temp]:
	LOAD
		  [Grant Activity Id]																			 AS [Grant Activity Id%]
		, [Source Organisation Id]																		 AS [Activity Source Organisation Id%]
		, IF([Activity Id] = '4-ENJBSQ2', 'a6c824bf-afc1-e611-80f1-c4346bc5977c', [PMC Region Id]) AS [PMC Region Id%]
		, [Programme Component Id]																		 AS [Programme Component Id%]
		, IF(LEN([Programme Id]) = 0, 'ae0b9448-9f69-e611-80e6-c4346bc43f98', [Programme Id]) AS [Programme Id%]
//		, [Grant Activity.Programme Id%]																				 AS [Programme Id%]
		, [Sub Programme]																				 AS [Sub Program]
		, [Grant Activity]																				 AS [Activity Title]
//		, [Grant Activity.Grant Activity Status]																		 AS [Grant Activity.Grant Activity Status]
		, [Activity Id]																					 AS [Activity Id]
		, [Activity Description]																			 AS [Long Description]
		, DATE([Activity Start Date], 'DD/MM/YYYY')														 AS [Activity Start Date]
		, DATE([Activity End Date], 'DD/MM/YYYY')														 AS [Activity End Date]
		, YEARNAME([Activity End Date], 0, 7)															 AS [Activity End Date Fin Year]
		, IF([Activity Start Date] > TODAY() - 30 AND [Activity Start Date] < TODAY(), 1, 0) AS [Activity started in last 30 days]
		, IF([Activity End Date] > TODAY() - 30 AND [Activity End Date] < TODAY(), 1, 0)	 AS [Activity ended in last 30 days]
//		, [Grant Activity.Funding Approved Date]																		 AS [Grant Activity.Funding Approved Date]
//		, [Grant Activity.Funding Approved By]																			 AS [Grant Activity.Funding Approved By]
		, [Source System Id]																			 AS [Grant Activity.Source System Id%]
//		, [Grant Activity.Source Activity Status]																		 AS [Grant Activity.Source Activity Status]
		, [Activity Manager]																				 AS [Activity Manager]
		, LOWER(TRIM([Activity Manager]))																 AS [Activity Manager Key]
		, [Approved On Date]																				 AS [Grant Activity.Approved On Date]
//		, [Grant Activity.Draft Coded By Id%]																			 AS [Grant Activity.Draft Coded By Id%]
//		, [Grant Activity.Draft Coded By]																				 AS [Grant Activity.Draft Coded By]
//		, [Grant Activity.Draft Approver Reject Code]																	 AS [Grant Activity.Draft Approver Reject Code]
//		, [Grant Activity.Draft Approver Reject]																		 AS [Grant Activity.Draft Approver Reject]
//		, [Grant Activity.Current Performance Outcome Id%]																 AS [Grant Activity.Current Performance Outcome Id%]
//		, [Grant Activity.Current Performance Outcome]																	 AS [Grant Activity.Current Performance Outcome]
//		, [Grant Activity.Source Status Group Code]																		 AS [Grant Activity.Source Status Group Code]
		, [Source Status Group]																			 AS [Activity Status]
//		, [Grant Activity.Mandatory Submission]																			 AS [Grant Activity.Mandatory Submission]
		, [Current Ceasing Activity Assessment Id]														 AS [Grant Activity.Current Ceasing Activity Assessment Id%]
		, [Current Ceasing Activity Assessment]															 AS [Grant Activity.Current Ceasing Activity Assessment]
//		, [Grant Activity.Has Review]																					 AS [Grant Activity.Has Review]
	FROM [lib://Curated Data Store:DataFiles/10 Landing Area/FUSION/Grant Activity.qvd] (qvd);
//WHERE LEN([Grant Activity.Programme Id%]) <> 0;


	LEFT JOIN
	LOAD
		  [Source Organisation Id]	 AS [Activity Source Organisation Id%]
		, [Organisation Id]		 AS [Activity Organisation Id%]
//		, [Source Organisation.Source System Id%]		 AS [Source Organisation.Source System Id%]
//		, [Source Organisation.Source System]			 AS [Source Organisation.Source System]
//		, [Source Organisation.Source Organisation Name]	 AS [Source Organisation.Source Organisation Name]
//		, [Source Organisation.Legal Entity Id]			 AS [Source Organisation.Legal Entity Id]
//		, [Source Organisation.Trading Name]			 AS [Source Organisation.Trading Name]
//		, [Source Organisation.ABN]						 AS [Source Organisation.ABN]
//		, [Source Organisation.Address Line]			 AS [Source Organisation.Address Line]
//		, [Source Organisation.State]					 AS [Source Organisation.State]
//		, [Source Organisation.Postcode]				 AS [Source Organisation.Postcode]
//		, [Source Organisation.Email Address]			 AS [Source Organisation.Email Address]
//		, [Source Organisation.Legal Name]				 AS [Source Organisation.Legal Name]
//		, [Source Organisation.Legal Entity Type]		 AS [Source Organisation.Legal Entity Type]
//		, [Source Organisation.Source Organisation Status]	 AS [Source Organisation.Source Organisation Status]
	FROM [lib://Curated Data Store:DataFiles/10 Landing Area/FUSION/Source Organisation.qvd] (qvd);


	LEFT JOIN
	LOAD
		  [Organisation Id]		 AS [Activity Organisation Id%]
		, [Organisation]			 AS [Activity Organisation]
//		, [Organisation.Entity Type Code]		 AS [Organisation.Entity Type Code]
//		, [Organisation.Entity Type]			 AS [Organisation.Entity Type]
		, [ABN]					 AS [Activity ABN]
//		, [Organisation.ASIC Number]			 AS [Organisation.ASIC Number]
//		, [Organisation.Email Address]			 AS [Organisation.Email Address]
//		, [Organisation.City]					 AS [Organisation.City]
//		, [Organisation.State]					 AS [Organisation.State]
//		, [Organisation.Postcode]				 AS [Organisation.Postcode]
//		, [Organisation.ORP Approved Date]		 AS [Organisation.ORP Approved Date]
		, [ORP Expiry Date]		 AS [Activity ORP Expiry Date]
		, IF(ISNULL([ORP Risk Rating]), 'Not Rated', IF([ORP Expiry Date] < TODAY(), 'Expired', [ORP Risk Rating])) AS [Activity Organisation Risk Profile]
//		, IF(ISNULL([Organisation.ORP Risk Rating]), 'Not Rated', [Organisation.ORP Risk Rating])	 AS [Activity Organisation Risk Profile]
//		, [Organisation.Risk Exemption Date]	 AS [Organisation.Risk Exemption Date]
//		, [Organisation.Risk Exemption Justification]	 AS [Organisation.Risk Exemption Justification]
		, [Risk Exemption Reason]	 AS [Actitivy Risk Exemption Reason]
//		, [Organisation.Indigenous Status]		 AS [Organisation.Indigenous Status]
		, IF(ISNULL([Indigeneity]) OR [Indigeneity] = 'Unknown', 'No', [Indigeneity]) AS [Organisation Indigeneity]
//		, [Organisation.Indigeneity Effective Date]	 AS [Organisation.Indigeneity Effective Date]
//		, [Organisation.Status]					 AS [Organisation.Status]
	FROM [lib://Curated Data Store:DataFiles/10 Landing Area/FUSION/Organisation.qvd] (qvd);


	LEFT JOIN
	LOAD
		  [Programme Id]						 AS [Programme Id%]
		, REPLACE([Programme], '2.', '1.')	 AS [Program]
	FROM [lib://Curated Data Store:DataFiles/10 Landing Area/FUSION/Programme.qvd] (qvd);


	LEFT JOIN
	LOAD
		  [Programme Component Id]	 AS [Programme Component Id%]
		, [Programme Id]			 AS [Programme Id%]
		, [Programme Component]		 AS [Programme Component.Programme Component]
//		, [Programme Component.ECJDM Applicable]		 AS [Programme Component.ECJDM Applicable]
//		, [Programme Component.Appropriation Type]		 AS [Programme Component.Appropriation Type]
		, [Outcome Element]			 AS [Outcome Element]
//		, [Programme Component.Status]					 AS [Programme Component.Status]
//		, [Programme Component.Alternate Name 1]		 AS [Programme Component.Alternate Name 1]
//		, [Programme Component.Alternate Name 2]		 AS [Programme Component.Alternate Name 2]
//		, [Programme Component.Alternate Name 3]		 AS [Programme Component.Alternate Name 3]
//		, [Programme Component.Alternate Name 4]		 AS [Programme Component.Alternate Name 4]
//		, [Programme Component.Alternate Name 5]		 AS [Programme Component.Alternate Name 5]
	FROM [lib://Curated Data Store:DataFiles/10 Landing Area/FUSION/Programme Component.qvd] (qvd);


	LEFT JOIN
	LOAD
		  [RGU Team / Section]					 AS [RGU Team]
		, [RGU Location]						 AS [RGU Location]
		, LOWER(TRIM([Name in Grants System]))	 AS [Activity Manager Key]
	FROM [lib://AppData/PROD/AzureDataLake/SSR/RGU Staff.qvd] (qvd);


	[Grant Activity Funding]:
	LOAD
//		  [Grant Activity Funding.Grant Activity Funding Id%]	 AS [Grant Activity Funding.Grant Activity Funding Id%]
		  [Grant Activity Id]	 AS [Grant Activity Id%]
		, [Financial Year Id]	 AS [Financial Year Id%]
//		, [Grant Activity Funding.Source Status Group]	 AS [Grant Activity Funding.Source Status Group]
//		, [Grant Activity Funding.Activity Funding]		 AS [Grant Activity Funding.Activity Funding]
		, [Funding Amount]		 AS [Total Value (ex GST)]
		, [Funds Released]		 AS [Funds Released (ex GST)]
//		, [Grant Activity Funding.Activity Funding Status]	 AS [Grant Activity Funding.Activity Funding Status]
	FROM [lib://Curated Data Store:DataFiles/10 Landing Area/FUSION/Grant Activity Funding.qvd] (qvd);


	LEFT JOIN
	LOAD
		  [Financial Year Id]	 AS [Financial Year Id%]
		, [Financial Year]		 AS [Activity Funding Financial Year]
	FROM [lib://Curated Data Store:DataFiles/10 Landing Area/FUSION/Financial Year.qvd] (qvd);


	[Grant Activity]:
	LOAD
		  [Grant Activity Id%]														 AS [Grant Activity Id%]
		, [Activity Id]																 AS [Activity Id]
//		, [PMC Region Id%]															 AS [PMC Region Id%]
		, [Activity Organisation Id%]												 AS [Activity Organisation Id%]
		, [Activity Organisation]													 AS [Activity Organisation]
		, [Activity ABN]															 AS [Activity ABN]
		, [Organisation Indigeneity]												 AS [Organisation Indigeneity]
		, [Activity Organisation Risk Profile]										 AS [Activity Organisation Risk Profile]
		, [Activity ORP Expiry Date]												 AS [Activity ORP Expiry Date]
		, [Activity Title]															 AS [Activity Title]
		, [Activity Status]															 AS [Activity Status]
		, IF([Outcome Element] = 'ABA', 'Aboriginals Benefit Account', [Program])	 AS [Program]
		, [Sub Program]																 AS [Sub Program]
		, [Activity Start Date]														 AS [Activity Start Date]
		, [Activity End Date]														 AS [Activity End Date]
		, [Activity End Date] - [Activity Start Date]								 AS [Activity Duration]
		, [Activity Manager]														 AS [Activity Manager]
		, IF(ISNULL([RGU Team]), 'Not in GMU', [RGU Team])							 AS [RGU Team]
		, IF(ISNULL([RGU Location]), 'Not in GMU', [RGU Location])					 AS [RGU Location]
		, [Activity started in last 30 days]										 AS [Activity started in last 30 days]
		, [Activity ended in last 30 days]											 AS [Activity ended in last 30 days]
		, [Activity End Date Fin Year]												 AS [Activity End Date Fin Year]
	RESIDENT [Grant Activity Temp];


	LatestFinYear:
	LOAD *
		, '20' & [LatestFinYear] - 1 & '-' & [LatestFinYear]	 AS [Latest Funding Financial Year];


	LOAD [Grant Activity Id%] AS [Grant Activity Id%]
		, MAX(RIGHT([Activity Funding Financial Year], 2))	 AS [LatestFinYear]
	RESIDENT [Grant Activity Funding]
	GROUP BY [Grant Activity Id%];
//WHERE [Activity Status] = 'Current';


	DROP TABLE [Grant Activity Temp];
// TempAcquittalTest:
// Load [Grant Activity Id%] as [Grant Activity Id%2],
// 	[Activity Id],  // AS [Act Id]
//     replace([Activity End Date Fin Year], '-20', '-') as [Activity End Date Fin Year2],
//     [Activity End Date] as [Activity End Date2]
//     Resident [Grant Activity];
// left Join
// Load [Grant Activity Id%] as [Grant Activity Id%2],
// 	[Activity Funding Financial Year] as [Activity Funding Financial Year2],
//     num(left([Activity Funding Financial Year],4)) + 1 &'-' & num(right([Activity Funding Financial Year],2)+1) as [Expected Acquittal Fin Year]
// Resident [Grant Activity Funding]
// where num(left([Activity Funding Financial Year],4)) > 2015;
// AcquittalTest:
// Load *, AutoNumber( [Activity Id]&[Match Acquittal Fin Year]) as Key;
// Load [Activity Id],
// 	[Activity Funding Financial Year2],
//     [Activity End Date Fin Year2],
//     [Activity End Date2],
//     [Expected Acquittal Fin Year],
// 	if([Activity End Date Fin Year2] <> [Activity Funding Financial Year2], [Expected Acquittal Fin Year],
//     	if (match(month([Activity End Date2]),'Apr','May','Jun'), [Expected Acquittal Fin Year],
//         	[Activity End Date Fin Year2])) as [Match Acquittal Fin Year],
//    num(month([Activity End Date2])) as mth
// resident TempAcquittalTest;
// left Join
// load AutoNumber([Activity Id] & [Acquittal Financial Year2]) as Key,
// //[Due Fin Year]
// 		[Acquittal Financial Year2],
//         [Acquittal Due Date2],
//         [Due Fin Year]
//         ;
// Load [Activity Id], //& [Acquittal Financial Year]) as Key ,
// 	[Acquittal Financial Year] as [Acquittal Financial Year2],
//     [Acquittal Due Date] as [Acquittal Due Date2],
//     replace(yearname([Acquittal Due Date],0,7), '-20', '-') as [Due Fin Year]
//         Resident  [Grant Activity Acquittal];
// drop table TempAcquittalTest;



///$tab Region
	RegionMap:
	MAPPING LOAD *
	INLINE [Region, Group
	Adelaide - GMU, Central
	Alice Springs - GMU,Central
    Arnhem Land & Groote Eylandt, Central
    Darwin - GMU,	Central
    Central Australia,	Central
    Top End & Tiwi Islands,	Central
    Brisbane - GMU,	Eastern
    Cairns - GMU,	Eastern
    Dubbo - GMU,	Eastern
    Mount Isa - GMU,	Eastern
    Orange - GMU,	Eastern
    Parramatta - GMU,	Eastern
    Tamworth - GMU,	Eastern
    Townsville - GMU,	Eastern
    Eastern NSW,	Eastern
    Eastern New South Wales, Eastern
    Western New South Wales, Eastern
    North Queensland,	Eastern
    South Queensland,	Eastern
    Eastern New South Wales,  Eastern
    Western NSW,	Eastern
    Broome - GMU,	National Office
    Canberra - GMU,	National Office
    Coffs Harbour - GMU,	National Office
    National Office,	National Office
    Adelaide - GMU,	West and South
    Melbourne - GMU,	West and South
    Perth - GMU,	West and South
    Greater Western Australia,	West and South
    Kimberley, West and South
    South Australia,	West and South
    Victoria & Tasmania,	West and South
    GMU Central Support - GMU, National Office
];


	[Grant Managing Region]:
	LOAD
		  [Grant Activity Id%]	 AS [Grant Activity Id%]
		, [NIAA Region Id%]		 AS [PMC Region Id%]
		, [GMU Region Id%]		 AS [GMU Region Id%]
		, [Engegement Officer]	 AS [Engegement Officer]
		, [Source System]		 AS [Source System]
	FROM [lib://AppData/PROD/AzureDataLake/GPS/Grant Managing Region.qvd] (qvd);


	[NIAA Region]:
	LOAD *
		, APPLYMAP('RegionMap', [NIAA Region])	 AS Group;


	LOAD
		  [PMC Region Id]																				 AS [PMC Region Id%]
//		, [PMC Region.PMC Region Code]																				 AS [PMC Region.PMC Region Code]
		, IF(MATCH([PMC Region Abbr], 'FNQLD', 'GNQLD'), [PMC Region])						 AS [NIAA Sub Region]
		, IF(MATCH([PMC Region Abbr], 'FNQLD', 'GNQLD'), [PMC Region Abbr])					 AS [NIAA Sub Region Abbr]
		, IF(MATCH([PMC Region Abbr], 'FNQLD', 'GNQLD'), 'North Queensland', [PMC Region])	 AS [NIAA Region]
		, IF(MATCH([PMC Region Abbr], 'FNQLD', 'GNQLD'), 'NQ', [PMC Region Abbr])				 AS [PMC Region.PMC Region Abbr]
		, [State]																						 AS [PMC Region.State]
//		, [PMC Region.Regional Manager]																				 AS [PMC Region.Regional Manager]
//		, [PMC Region.Regional Manager Email]																		 AS [PMC Region.Regional Manager Email]
//		, [PMC Region.Regional Manager Business Phone]																 AS [PMC Region.Regional Manager Business Phone]
//		, [PMC Region.Regional Manager Mobile]																		 AS [PMC Region.Regional Manager Mobile]
		, IF([PMC Region Abbr] = 'GWA' OR [PMC Region Abbr] = 'KIM' OR [PMC Region Abbr] = 'SA' OR [PMC Region Abbr] = 'VIC/TAS', 'West & South Group',
			IF([PMC Region Abbr] = 'CA' OR [PMC Region Abbr] = 'TETI' OR [PMC Region Abbr] = 'ALGE', 'Central Group',
			IF([PMC Region Abbr] = 'ENSW' OR [PMC Region Abbr] = 'WNSW' OR [PMC Region Abbr] = 'SQLD'
			OR [PMC Region Abbr] = 'FNQLD' OR [PMC Region Abbr] = 'GNQLD', 'Eastern Group', 'National'))) AS [NIAA Region Group]
	FROM [lib://Curated Data Store:DataFiles/10 Landing Area/FUSION/PMC Region.qvd] (qvd);


	[GMU Region]:
	LOAD
		  [PMC Region Id]													 AS [GMU Region Id%]
		, [State]															 AS [GMU State]
		, IF([PMC Region Abbr] = 'GWA' OR [PMC Region Abbr] = 'KIM' OR [PMC Region Abbr] = 'SA' OR [PMC Region Abbr] = 'VIC/TAS', 'West & South Group',
			IF([PMC Region Abbr] = 'CA' OR [PMC Region Abbr] = 'TETI' OR [PMC Region Abbr] = 'ALGE', 'Central Group',
			IF([PMC Region Abbr] = 'ENSW' OR [PMC Region Abbr] = 'WNSW' OR [PMC Region Abbr] = 'SQLD' OR [PMC Region Abbr] = 'FNQLD'
			OR [PMC Region Abbr] = 'GNQLD', 'Eastern Group', 'National')))	 AS [GMU Region Group]
	FROM [lib://Curated Data Store:DataFiles/10 Landing Area/FUSION/PMC Region.qvd] (qvd);
///$tab Milestone
	[Grant Activity Milestone]:
	LET vDaysoverdue = 'IF([Grant Activity Milestone.Milestone Expected Due Date] <= today(), Today() - [Grant Activity Milestone.Milestone Expected Due Date])' ;
LET vEndDate = TEXT('2014-06-30');


//		  LEFT KEEP([Grant Activity Acquittal])
	LOAD $([vDaysoverdue]) AS [Number of Days Milestone Overdue]
		, [Activity Id]														 AS [Grant Activity Milestone.Activity Id]
		, REPLACE(YEARNAME([Milestone Expected Due Date], 0, 7), '-20', '-')	 AS [Milestone Financial Year]
		, [Activity PBS Program]												 AS [Activity PBS Outcome]
		, [Managing Office - Activity]											 AS [Milestone Managing Office%]
		, [Milestone Id]														 AS [Milestone Id]
		, [Milestone Status]													 AS [Grant Activity Milestone.Milestone Status]
		, IF([Milestone Expected Due Date] > TODAY(), 'Overdue', [Milestone Stage]) AS [Grant Activity Milestone.Milestone Stage]
		, [Milestone Completed Indicator]										 AS [Milestone Completed Indicator]
		, [Milestone Payment Mode]												 AS [Milestone Payment Mode]
		, [Milestone Received]													 AS [Grant Activity Milestone.Milestone Received]
		, [Milestone Short Description]										 AS [Grant Activity Milestone.Milestone Short Description]
		, [Milestone Long Description]											 AS [Milestone Long Description]
		, [Milestone Completion Description]									 AS [Milestone Completion Description]
		, [Milestone Type]														 AS [Milestone Type]
		, (FLOOR(([Milestone Completion Date] - [Milestone Expected Due Date]) / 30) * 30) + 30 AS [Days to Complete]
		, [Milestone Expected Due Date]										 AS [Milestones Expected Due Date]
		, [Financial Year Name]												 AS [Grant Activity Milestone.Financial Year Name]
		, [Milestone Action Required]											 AS [Grant Activity Milestone.Milestone Action Required]
		, [Milestone Completion Date]											 AS [Milestone Completion Date]
		, [Activity IMPACT PO Id]												 AS [Grant Activity Milestone.Activity IMPACT PO Id]
		, [Milestone Auto Release Indicator]									 AS [Grant Activity Milestone.Milestone Auto Release Indicator]
		, [Milestone Date Driven Indicator]									 AS [Grant Activity Milestone.Milestone Date Driven Indicator]
		, [Milestone Actual Amount Ex GST]										 AS [Milestone Actual Amount Ex GST]
		, IF([Milestone Expected Due Date] > TODAY(), 0, 1)					 AS [Overdue by Date]
		, IF([Milestone Expected Due Date] <= TODAY(),
			IF([Milestone Stage] = 'Future', 'Overdue - Not received',
			IF([Milestone Stage] = 'Overdue', 'Overdue - Not received',
			IF([Milestone Stage] = 'Received', 'Overdue - Received'))),
			IF([Milestone Expected Due Date] > TODAY(),
			IF([Milestone Stage] = 'Future', 'Future - Not received',
			IF([Milestone Stage] = 'Overdue', 'Future - Not received',
			IF([Milestone Stage] = 'Received', 'Future - Received'))))
			)																							 AS [Stage]
		, IF([Milestone Expected Due Date] < TODAY() + 30 AND [Milestone Expected Due Date] > TODAY(), 1, 0) AS [Due in next 30 Days]
		, IF([Milestone Expected Due Date] < TODAY() + 180 AND [Milestone Expected Due Date] > TODAY(), 1, 0) AS [Due in next 6 Months]
		, IF([Milestone Expected Due Date] < TODAY() + 60 AND [Milestone Expected Due Date] > TODAY() + 30, 1, 0) AS [Due in next 60 Days]
		, IF([Milestone Completion Date] > TODAY() - 30 AND [Milestone Expected Due Date] < TODAY(), 1, 0) AS [Completed in last 30 Days]
		, IF($([vDaysoverdue]) <= 30, 1, 0)																 AS [Due in last 30 Days]
	FROM [lib://Curated Data Store:DataFiles/10 Landing Area/GPS/Grant Activity Milestone - Old.qvd] (qvd)
	WHERE [Activity Execution State] = 'Executed' AND [Milestone Status] = 'Current'
	AND MATCH([Activity Status], 'Approved', 'Varied', 'Ready for Approval')
	AND ([Activity PBS Program] <> 'DPMC SOETM Services for Other Entities and Trust Monies')
	AND ([Milestone Type] LIKE '*Acquittal*' OR [Milestone Long Description] LIKE '*Acquittal*');


	NOCONCATENATE
	[Milestone Count]:
	LOAD COUNT([Milestone Id]) AS [Milestone Count]
		, [Grant Activity Milestone.Activity Id]	 AS [Activity Id]
	RESIDENT [Grant Activity Milestone]
	GROUP BY [Grant Activity Milestone.Activity Id];

LET vLastYear = NUM(YEAR(TODAY()) - 1);
	[Milestone Overdue Month]:
	LOAD
		  [Milestone Id]										 AS [Milestone Id]
		, [Milestone Payment Mode]								 AS [Overdue Payment Mode]
		, DATE([Outstanding], 'dd/MM/yyyy')						 AS [Milestone Outstanding]
		, REPLACE(YEARNAME([Outstanding], 0, 7), '-20', '-')	 AS [Overdue Milestone Financial Year]
	FROM [lib://Curated Data Store:DataFiles/10 Landing Area/GPS/Milestone Overdue Month.qvd] (qvd);




///$tab Quality
	[Grant Activity Acquittal Error]:
	LOAD
		  [Review Id]	 AS [Review Id]
		, [Error]		 AS [Review Error]
		, [Error Number]	 AS [Error Number]
	FROM [lib://Curated Data Store:DataFiles/10 Landing Area/GPS/Grant Activity Acquittal Error.qvd] (qvd);


//Check for missing acquittals by comparing the number of financial years with the number of reviews 
	FinYearCount:
	LOAD [Grant Activity Id%] AS [Grant Activity Id%]
		, COUNT([Activity Funding Financial Year])	 AS [FundingYrCount]
	RESIDENT [Grant Activity Funding]
	WHERE NUM(LEFT([Activity Funding Financial Year], 4)) > 2016
//Exclude next financial year
	AND NUM(LEFT([Activity Funding Financial Year], 4)) <= NUM(LEFT(YEARNAME(NOW(2), 0, 7), 4))
	GROUP BY [Grant Activity Id%];


	LEFT JOIN
	LOAD [Grant Activity Id%] AS [Grant Activity Id%]
		, [Activity Id]	 AS [Activity Id]
	RESIDENT [Grant Activity];


	[Acquittal Count]:
	LOAD [Activity Id] AS [Activity Id]
		, COUNT([Review Id])	 AS [ReviewCount]
	RESIDENT [Grant Activity Acquittal]
	GROUP BY [Activity Id];


	Stg_MissingAcquittals:
	LOAD [Activity Id] AS [Activity Id]
		, [FundingYrCount]	 AS [FundingYrCount]
	RESIDENT FinYearCount;


	LEFT JOIN
	LOAD [Activity Id] AS [Activity Id]
		, [ReviewCount]	 AS [ReviewCount]
	RESIDENT [Acquittal Count];


	MissingAcquittals:
	LOAD [Activity Id] AS [Activity Id]
		, [FundingYrCount]												 AS [FundingYrCount]
		, [ReviewCount]													 AS [ReviewCount]
		, IF([FundingYrCount] > ALT([ReviewCount], 0), 'Check', 'Ok')	 AS [Potential Missing Acquittal]
	RESIDENT Stg_MissingAcquittals;


	DROP TABLES [Acquittal Count], FinYearCount, Stg_MissingAcquittals;



///$tab Exit
	EXIT SCRIPT;
